# Generated by Django 4.2.7 on 2023-11-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=250)),
                ('zanr', models.CharField(max_length=200)),
                ('uloge', models.CharField(max_length=350)),
            ],
        ),
    ]
